apiVersion: apps/v1
kind: Deployment
metadata:
  name: nuclear-analytics
  namespace: nuclear-app
  labels:
    app: nuclear-security
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nuclear-security
  template:
    metadata:
      labels:
        app: nuclear-security
    spec:
      initContainers:
      - name: data-load
        image: yanavyklyuk/nuclear-data-load:latest
        envFrom:
        - configMapRef:
            name: nuclear-config
        volumeMounts:
        - name: shared-db
          mountPath: /app/db/init
      - name: data-quality
        image: yanavyklyuk/nuclear-quality:latest
        envFrom:
        - configMapRef:
            name: nuclear-config
        volumeMounts:
        - name: shared-db
          mountPath: /app/db/init
        - name: shared-reports
          mountPath: /app/reports
      - name: data-research
        image: yanavyklyuk/nuclear-research:latest
        envFrom:
        - configMapRef:
            name: nuclear-config
        volumeMounts:
        - name: shared-db
          mountPath: /app/db/init
        - name: shared-reports
          mountPath: /app/reports
      - name: visualization
        image: yanavyklyuk/nuclear-visualization:latest
        envFrom:
        - configMapRef:
            name: nuclear-config
        volumeMounts:
        - name: shared-db
          mountPath: /app/db/init
        - name: shared-reports
          mountPath: /app/reports
      containers:
      - name: web-app
        image: yanavyklyuk/nuclear-web:latest
        ports:
        - containerPort: 8501
        envFrom:
        - configMapRef:
            name: nuclear-config
        volumeMounts:
        - name: shared-reports
          mountPath: /app/reports
      volumes:
      - name: shared-db
        emptyDir: {}
      - name: shared-reports
        emptyDir: {}