name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
    inputs:
      module:
        description: "Оберіть модуль для запуску"
        required: true
        default: "all"
        type: choice
        options:
          - all
          - data_load
          - data_quality_analysis
          - models
          - visualization

env:
  FORCE_JAVASCRIPT_ACTIONS_TO_NODE24: true

jobs:
  changes:
    runs-on: ubuntu-latest
    outputs:
      modules: ${{ steps.set-matrix.outputs.modules }}
    steps:
      - uses: actions/checkout@v4

      - uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            data_load: 'src/data_load.py'
            data_quality_analysis: 'src/data_quality_analysis.py'
            models: 'src/models.py'
            visualization: 'src/visualization.py'

      - name: Generate Matrix Config
        id: set-matrix
        shell: bash
        run: |
          if [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            if [ "${{ github.event.inputs.module }}" == "all" ]; then
              echo 'modules=["data_load","data_quality_analysis","models","visualization"]' >> $GITHUB_OUTPUT
            else
              echo "modules=[\"${{ github.event.inputs.module }}\"]" >> $GITHUB_OUTPUT
            fi
          else
            modules=()
          
            if [[ "${{ steps.filter.outputs.data_load }}" == "true" ]]; then
              modules+=('"data_load"')
            fi
            if [[ "${{ steps.filter.outputs.data_quality_analysis }}" == "true" ]]; then
              modules+=('"data_quality_analysis"')
            fi
            if [[ "${{ steps.filter.outputs.models }}" == "true" ]]; then
              modules+=('"models"')
            fi
            if [[ "${{ steps.filter.outputs.visualization }}" == "true" ]]; then
              modules+=('"visualization"')
            fi
          
            IFS=,
            json="[${modules[*]}]"
            echo "modules=$json" >> $GITHUB_OUTPUT
          fi

  run-modules:
    needs: changes
    if: ${{ needs.changes.outputs.modules != '[]' && needs.changes.outputs.modules != '' }}
    runs-on: ubuntu-latest

    env:
      PYTHONPATH: ${{ github.workspace }}/src

    strategy:
      fail-fast: false
      matrix:
        module: ${{ fromJSON(needs.changes.outputs.modules) }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          cache: "pip"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Prepare Data Environment
        run: |
          mkdir -p data/raw
          cp data/test/nuclear_safety_test.xlsx data/raw/nuclear_safety_q4_2025.xlsx

      - name: Run Module Script
        run: |
          mkdir -p artifacts/${{ matrix.module }}
          python src/${{ matrix.module }}.py > artifacts/${{ matrix.module }}/run.log 2>&1
          
          if [ "${{ matrix.module }}" == "visualization" ]; then
            echo "Копіювання графіків до артефактів"
            cp reports/figures/*.png artifacts/${{ matrix.module }}/ 2>/dev/null || echo "Графіків не знайдено"
          fi

      - name: Run Tests
        run: |
          if [ -f tests/test_${{ matrix.module }}.py ]; then
            pytest tests/test_${{ matrix.module }}.py
          else
            echo "Тестів для ${{ matrix.module }} не знайдено."
          fi

      - name: Upload Artifacts
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: results-${{ matrix.module }}
          path: artifacts/${{ matrix.module }}/
          retention-days: 5

  deploy-pages:
    needs: run-modules
    if: always() && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - uses: actions/checkout@v4

      - name: Download Artifacts
        uses: actions/download-artifact@v4
        with:
          name: results-visualization
          path: ./temp_artifacts

      - name: Prepare Web Page
        run: |
          mkdir -p public
          
          find ./temp_artifacts -name "*.png" -exec cp {} public/ \;
          
          echo "<html><body style='font-family: Arial; padding: 40px; text-align: center;'>" > public/index.html
          echo "<h1>Звіт з аналізу даних</h1>" >> public/index.html
          echo "<p>Оновлено: $(date)</p><hr>" >> public/index.html
          
          cd public
          if ls *.png 1> /dev/null 2>&1; then
            for img in *.png; do
              echo "<h3>$img</h3><img src='$img' style='max-width: 800px; border: 1px solid #ddd; margin-bottom: 20px;'><br>" >> index.html
            done
          else
            echo "<h3>Помилка: Файли знайдено в артефактах, але не скопійовано</h3>" >> index.html
          fi
          echo "</body></html>" >> index.html

      - name: Deploy
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public